### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by morgansobol** [d-mcgrath/MetaPathPredict#3]
Hi there,

I am trying to install MetaPathPredict.
I downloaded the git repository and ran `python3 install.py build` then `python3 install.py install`.
However when I run MetaPathPredict --help I get this error:

> Traceback (most recent call last):
>   File "/opt/miniconda3/envs/py3/bin/MetaPathPredict", line 33, in <module>
>     sys.exit(load_entry_point('metapathpredict==0.0.0', 'console_scripts', 'MetaPathPredict')())
>   File "/opt/miniconda3/envs/py3/bin/MetaPathPredict", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/opt/miniconda3/envs/py3/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/opt/miniconda3/envs/py3/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'metapathpredict'

Maybe there is an issue with where I am trying to install and so it cannot find anything? Is there a way to set the install directory?

Much thanks,
Morgan

**Comment by d-mcgrath** [comment]
Hi Morgan,

Thank you for your interesting in MetaPathPredict, and for sending me the stack traceback for this error! I'm looking into this and will push a fix asap.

Best,
David

**Comment by d-mcgrath** [comment]
Hi Morgan,

I pushed a fix and updated the install instructions. Could you give it a try and see if you can install it now?

Thanks,
David

**Comment by morgansobol** [comment]
Thanks David!
Sorry, I’ve been a little busy but I’ll try it out shortly and report back!

On Oct 15, 2023, at 8:46 PM, David Geller-McGrath ***@***.***> wrote:

﻿

Hi Morgan,

I pushed a fix and updated the install instructions. Could you give it a try and see if you can install it now?

Thanks,
David

**Comment by morgansobol** [comment]
Hi David,

The install worked well and I got MetaPathPredict successfully running with the test data, so big thanks!! 
But I am struggling to get my actual files to work. I'm pretty certain it has to do with file formatting. I actually used hmmer to get the KOs and then simplified my data to have one file for each genome and their kos. Here is an example of a data frame:

> accession_1	K21029	moeB; molybdopterin-synthase adenylyltransferase [EC:2.7.7.80]
> accession_2	K22391	E3.5.4.16; GTP cyclohydrolase I [EC:3.5.4.16]
> accession_3	K08303	prtC, trhP; U32 family peptidase [EC:3.4.-.-]
> accession_4	K00945	cmk; CMP/dCMP kinase [EC:2.7.4.25]
> accession_5	K02876	RP-L15, MRPL15, rplO; large subunit ribosomal protein L15
> accession_6	K03595	era, ERAL1; GTPase
> accession_7	K22585	nreA; DNA repair protein NreA
> accession_8	K03500	rsmB, sun; 16S rRNA (cytosine967-C5)-methyltransferase [EC:2.1.1.176]
> accession_9	K14540	rbgA; ribosome biogenesis GTPase A
> accession_10	K00598	tam; trans-aconitate 2-methyltransferase [EC:2.1.1.144]

Here is the error I get even though I checked that I had three columns, which I *think* the error is complaining about?

> Traceback (most recent call last):
>   File "/home/msobol/.conda/envs/MetaPathPredict/bin/MetaPathPredict", line 8, in <module>
>     sys.exit(Models.predict())
>   File "/home/msobol/.conda/envs/MetaPathPredict/lib/python3.10/site-packages/metapathpredict/MetaPathPredict.py", line 545, in predict
>     files_list.read_koala_tsv()
>   File "/home/msobol/.conda/envs/MetaPathPredict/lib/python3.10/site-packages/metapathpredict/utils.py", line 221, in read_koala_tsv
>     data = pd.DataFrame(lines)[[0,1,2]]
>   File "/home/msobol/.conda/envs/MetaPathPredict/lib/python3.10/site-packages/pandas/core/frame.py", line 3811, in __getitem__
>     indexer = self.columns._get_indexer_strict(key, "columns")[1]
>   File "/home/msobol/.conda/envs/MetaPathPredict/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6113, in _get_indexer_strict
>     self._raise_if_missing(keyarr, indexer, axis_name)
>   File "/home/msobol/.conda/envs/MetaPathPredict/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6173, in _raise_if_missing
>     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
> KeyError: "None of [Int64Index([0, 1, 2], dtype='int64')] are in the [columns]"

I am running `MetaPathPredict -i inputs/*.txt -a koala -o results/`

I appreciate your help!
Morgan

**Comment by d-mcgrath** [comment]
Hi Morgan,

That's interesting! I'll add a method to read in custom datasets like this one, and let you know when it's ready.

Best,
David

**Comment by morgansobol** [comment]
Thanks David! 
I formatted my file to match the blastKoala format in the annotation_examples/ directory.
My file has the accession #, KO #, and then the description in the third column (as above). 
So I am not sure what else is missing for MetaPathPredict to recognize the file. 

Best,
Morgan

**Comment by morgansobol** [comment]
Hi again,

I just realized that I get the same error when I test the blastKoala example file and set -a koala.
But MetaPathPredict works fine when I use the kofamscan file and -a kofamscan

So maybe there is something wrong with the way MetaPathPredict reads the koala formatted files. Does it work for you?

Best,
Morgan

**Comment by d-mcgrath** [comment]
Hi Morgan, 

I was able to reproduce your error on my end. Thank you for catching that! Please go ahead and re-install and download all MetaPathPredict files and models. I updated the koala function, and it should work now. I'll add another read-in function for custom data inputs soon as well.

Best,
David

**Comment by morgansobol** [comment]
Hi David, 

It worked on my BlastKoala-formatted hmmer output! :)

Thanks a bunch!!
Morgan

**Comment by d-mcgrath** [comment]
Hi Morgan,

Great, thanks for letting me know! Going to close this.

Best,
David
