### ISSUE TITLE
Interested in modules not available in current version

### ISSUE THREAD

**Issue by iochatz** [d-mcgrath/MetaPathPredict#4]
Hi,

Great tool! I have tried MetaPathPredict on MAGs with varying quality (completion/contamination) and found it way more robust than other tools.
My issue is that I am interested in some modules that are currently not included in the tool and I was wondering if you are planning to include more modules in the future.

Best regards,
Ioanna

**Comment by d-mcgrath** [comment]
Hi Ioanna,

Thank you for your interest in MetaPathPredict! I am planning to add more modules in the future, especially as more bacterial genome data becomes available. If there are some specific modules you would be interested in to be included, please feel free to email me them: mcgrath1 [at] mit.edu.

All the best,
David
